### PR TITLE
JOB-6

### PR DESCRIPTION
**Pull request by 0812Sean**

### CODE REVIEW

**Comment by mengzhuou** [comment]
image

Either position the picker at the right, or shorten the width of time picker

**Comment by mengzhuou** [comment]
Make Comment optional. Make other input have "*" red mark meaning it's mandatory

**Comment by mengzhuou** [comment]
image
Make this display "Wecome, [Username]"

Get username from google sign in

**Comment by mengzhuou** [comment]
> image
> Either position the picker at the right, or shorten the width of time picker

Make sure date picker do not show date after today

**Comment by 0812Sean** [comment]
Make Comment optional. Make other input have "*" red mark meaning it's mandatory。

**Comment by 0812Sean** [comment]
date picker do not show date after today

**Pull request merged**
